name = input("Enter name: ")
roll = int(input("Enter roll number: "))
ispass = eval(input("Enter True for pass and False for fail: "))
print("Student Information:")
print("Name: ", name)
print("Roll Number: ", roll)
print("Result: ", ispass)
